dev.com/config/routes.rb
DevCom::Application.routes.draw do
  resources :cars

  resources :trucks

  resources :books

end

dev.com/app/models/bike.rb
class Bike < ActiveRecord::Base
  include DuckTest::LoggerHelper

  #validates_presence_of :make

  before_save :do_something

  def do_something
    ducklog.console "................................... bike"
    return true
  end

end

dev.com/app/models/book.rb
class Book < ActiveRecord::Base

  before_save :my_save

  def my_save
#     return false
    return true
  end

  def my_method
    return "yesz"
  end
  
end

dev.com/app/models/car.rb
class Car < ActiveRecord::Base
end

dev.com/app/models/truck.rb
class Truck < ActiveRecord::Base
end

dev.com/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

dev.com/app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  # GET /bikes
  # GET /bikes.json
  def index
    @bikes = Bike.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bikes }
    end
  end

  # GET /bikes/1
  # GET /bikes/1.json
  def show
    @bike = Bike.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bike }
    end
  end

  # GET /bikes/new
  # GET /bikes/new.json
  def new
    @bike = Bike.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bike }
    end
  end

  # GET /bikes/1/edit
  def edit
    @bike = Bike.find(params[:id])
  end

  # POST /bikes
  # POST /bikes.json
  def create
    @bike = Bike.new(params[:bike])

    respond_to do |format|
      if @bike.save
        format.html { redirect_to @bike, notice: 'Bike was successfully created.' }
        format.json { render json: @bike, status: :created, location: @bike }
      else
        format.html { render action: "new" }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bikes/1
  # PUT /bikes/1.json
  def update
    @bike = Bike.find(params[:id])

    respond_to do |format|
      if @bike.update_attributes(params[:bike])
        format.html { redirect_to @bike, notice: 'Bike was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1
  # DELETE /bikes/1.json
  def destroy
    @bike = Bike.find(params[:id])
    @bike.destroy

    respond_to do |format|
      format.html { redirect_to bikes_url }
      format.json { head :ok }
    end
  end
end

dev.com/app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :ok }
    end
  end
end

dev.com/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :ok }
    end
  end
end

dev.com/app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  # GET /trucks
  # GET /trucks.json
  def index
    @trucks = Truck.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trucks }
    end
  end

  # GET /trucks/1
  # GET /trucks/1.json
  def show
    @truck = Truck.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @truck }
    end
  end

  # GET /trucks/new
  # GET /trucks/new.json
  def new
    @truck = Truck.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @truck }
    end
  end

  # GET /trucks/1/edit
  def edit
    @truck = Truck.find(params[:id])
  end

  # POST /trucks
  # POST /trucks.json
  def create
    @truck = Truck.new(params[:truck])

    respond_to do |format|
      if @truck.save
        format.html { redirect_to @truck, notice: 'Truck was successfully created.' }
        format.json { render json: @truck, status: :created, location: @truck }
      else
        format.html { render action: "new" }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trucks/1
  # PUT /trucks/1.json
  def update
    @truck = Truck.find(params[:id])

    respond_to do |format|
      if @truck.update_attributes(params[:truck])
        format.html { redirect_to @truck, notice: 'Truck was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trucks/1
  # DELETE /trucks/1.json
  def destroy
    @truck = Truck.find(params[:id])
    @truck.destroy

    respond_to do |format|
      format.html { redirect_to trucks_url }
      format.json { head :ok }
    end
  end
end

dev.com/app/helpers/application_helper.rb
module ApplicationHelper
end

dev.com/app/helpers/bikes_helper.rb
module BikesHelper
end

dev.com/app/helpers/books_helper.rb
module BooksHelper
end

dev.com/app/helpers/cars_helper.rb
module CarsHelper
end

dev.com/app/helpers/trucks_helper.rb
module TrucksHelper
end

dev.com/app/views/bikes/_form.html.erb
<%= form_for(@bike) do |f| %>
  <% if @bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
      <% @bike.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dev.com/app/views/bikes/edit.html.erb
<h1>Editing bike</h1>

<%= render 'form' %>

<%= link_to 'Show', @bike %> |
<%= link_to 'Back', bikes_path %>

dev.com/app/views/bikes/index.html.erb
<h1>Listing bikes</h1>

<table>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bikes.each do |bike| %>
  <tr>
    <td><%= bike.make %></td>
    <td><%= bike.model %></td>
    <td><%= link_to 'Show', bike %></td>
    <td><%= link_to 'Edit', edit_bike_path(bike) %></td>
    <td><%= link_to 'Destroy', bike, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bike', new_bike_path %>

dev.com/app/views/bikes/new.html.erb
<h1>New bike</h1>

<%= render 'form' %>

<%= link_to 'Back', bikes_path %>

dev.com/app/views/bikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Make:</b>
  <%= @bike.make %>
</p>

<p>
  <b>Model:</b>
  <%= @bike.model %>
</p>


<%= link_to 'Edit', edit_bike_path(@bike) %> |
<%= link_to 'Back', bikes_path %>

dev.com/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dev.com/app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

dev.com/app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Author</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.author %></td>
    <td><%= book.title %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

dev.com/app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

dev.com/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author:</b>
  <%= @book.author %>
</p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

dev.com/app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dev.com/app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

dev.com/app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.make %></td>
    <td><%= car.model %></td>
    <td><%= link_to 'Show', car %></td>
    <td><%= link_to 'Edit', edit_car_path(car) %></td>
    <td><%= link_to 'Destroy', car, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Car', new_car_path %>

dev.com/app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

dev.com/app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Make:</b>
  <%= @car.make %>
</p>

<p>
  <b>Model:</b>
  <%= @car.model %>
</p>


<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

dev.com/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevCom</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

dev.com/app/views/trucks/_form.html.erb
<%= form_for(@truck) do |f| %>
  <% if @truck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@truck.errors.count, "error") %> prohibited this truck from being saved:</h2>

      <ul>
      <% @truck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dev.com/app/views/trucks/edit.html.erb
<h1>Editing truck</h1>

<%= render 'form' %>

<%= link_to 'Show', @truck %> |
<%= link_to 'Back', trucks_path %>

dev.com/app/views/trucks/index.html.erb
<h1>Listing trucks</h1>

<table>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trucks.each do |truck| %>
  <tr>
    <td><%= truck.make %></td>
    <td><%= truck.model %></td>
    <td><%= link_to 'Show', truck %></td>
    <td><%= link_to 'Edit', edit_truck_path(truck) %></td>
    <td><%= link_to 'Destroy', truck, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Truck', new_truck_path %>

dev.com/app/views/trucks/new.html.erb
<h1>New truck</h1>

<%= render 'form' %>

<%= link_to 'Back', trucks_path %>

dev.com/app/views/trucks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Make:</b>
  <%= @truck.make %>
</p>

<p>
  <b>Model:</b>
  <%= @truck.model %>
</p>


<%= link_to 'Edit', edit_truck_path(@truck) %> |
<%= link_to 'Back', trucks_path %>